FROM php:fpm

RUN apt-get update && apt-get install -y \
    git \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    libpq-dev 
     
RUN docker-php-ext-install \
    zip \
    intl \
    pdo_pgsql  

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY symfony/ /var/www/symfony
WORKDIR /var/www/symfony/
