FROM php:fpm

RUN apt-get update && apt-get install -y \
    git \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    libpq-dev \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd
     
RUN docker-php-ext-install \
    zip \
    intl \
    pdo_pgsql  

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY symfony/ /var/www/symfony
WORKDIR /var/www/symfony/
